### PR TITLE
implement header #1  bug fixed

### PR DESCRIPTION
**Pull request by CoderRedwing**
kindly accept my pr

### CODE REVIEW

**Comment by devvsakib** [comment]
you are not assigned to any issue

**Comment by CoderRedwing** [comment]
> you are not assigned to any issue
any issue with these bug I am fixed it

**Comment by devvsakib** [comment]
You are supposed not to do the footer bro. Merging your PR, But don't do it anywhere without assigning to any issues

**Review by devvsakib — APPROVED** [review]

**Comment by CoderRedwing** [comment]
@devvsakib okay bro

**Pull request merged**
