### PR TITLE
Featured profile section

### LINKED ISSUE #21: feature profile section slider using swiperjs
**Is your feature request related to a problem? Please describe.**
image

create this feature profile section as closely as possible. use swiperjs

Figma: https://www.figma.com/file/zwLA88lKxJl5Hg8R3eDCDb/hacktoberfest?type=design&node-id=0%3A1&mode=design&t=eNqzoLkTKfEbikim-1

### PR DESCRIPTION
**Pull request by NegativE333**
### Pull Request Summary

This pull request addresses the issue #21 , which required adding Swiper.js for a featured profile section. The changes in this pull request include:

- Added Swiper.js for creating an interactive featured profile section.
- Implemented a profile card hover effect that enhances the user experience.

Closes #21 

### Changes Made

1. **Added Swiper.js for Featured Profiles:**
   - Integrated Swiper.js to create an interactive featured profile section.
   - Utilized Swiper's navigation functionality for seamless profile navigation.

2. **Profile Card Hover Effect:**
   - Added a hover effect to profile cards, enhancing user engagement.
   - Profile cards change appearance on hover, providing a more interactive user experience.

### Screenshot
image

### CODE REVIEW

**Comment by devvsakib** [comment]
why did you delete this branch?

**Comment by NegativE333** [comment]
In the deployed version of the application, an issue has been observed where the profile cards within the featured profile section are overlapping on top of each other.
image

**Comment by devvsakib** [comment]
not responsive thats why

**Comment by NegativE333** [comment]
I will try to resolve this issue and create another pull request.

**Pull request closed without merging**
